name = "dev-extension"
main = "src/index.js"
compatibility_date = "2024-03-21"

[site]
bucket = "./build"

[build]
command = "npm run build"
output_dir = "build"

[env.production]
workers_dev = true